# Generated by Django 6.0.6 on 2026-06-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do usuário (único no sistema).', max_length=150, unique=True, verbose_name='Nome')),
                ('role', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('USUARIO', 'Usuário')], default='USUARIO', help_text='Papel do usuário: ADMINISTRADOR ou USUARIO.', max_length=20, verbose_name='Permissão')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['name'],
            },
        ),
    ]
