services:
  - type: web
    name: kanban-backend
    runtime: python
    plan: free
    buildCommand: >-
      pip install -r requirements.txt &&
      python manage.py collectstatic --no-input
    preDeployCommand: python manage.py migrate --noinput
    startCommand: >-
      python manage.py migrate --noinput &&
      gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.13"
