# Generated by Django 6.0.6 on 2026-06-24 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Título da tarefa (máx. 255 caracteres).', max_length=255, verbose_name='Nome')),
                ('status', models.CharField(choices=[('A_FAZER', 'A Fazer'), ('EM_PROGRESSO', 'Em Progresso'), ('PRONTO', 'Pronto'), ('ENTREGUE', 'Entregue')], default='A_FAZER', help_text='Estágio atual da tarefa no quadro Kanban.', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, help_text='Detalhes da tarefa (opcional).', verbose_name='Descrição')),
                ('story_points', models.PositiveSmallIntegerField(blank=True, help_text='Estimativa de esforço, de 0 a 100 (opcional).', null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Story Points')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Preenchida automaticamente na criação da tarefa.', verbose_name='Data de Criação')),
                ('due_date', models.DateTimeField(blank=True, help_text='Prazo da tarefa (opcional).', null=True, verbose_name='Data Limite')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Preenchida quando a tarefa é concluída (opcional).', null=True, verbose_name='Data de Fechamento')),
                ('creator', models.ForeignKey(help_text='Usuário que criou a tarefa (obrigatório, exatamente um).', on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to='users.user', verbose_name='Criador')),
                ('responsibles', models.ManyToManyField(blank=True, help_text='Usuários responsáveis pela tarefa (nenhum ou vários).', related_name='assigned_tasks', to='users.user', verbose_name='Responsáveis')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-created_at'],
            },
        ),
    ]
