# Generated by Django 6.0.6 on 2026-06-24 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator_name',
            field=models.CharField(blank=True, help_text='Nome do criador armazenado de forma desnormalizada (cópia). É preenchido na criação, atualizado quando o criador se renomeia e passa a "[DELETADO] <último nome>" quando a conta é excluída. Permite obter o nome do criador sem consultar a tabela de usuários.', max_length=170, verbose_name='Nome do Criador'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(help_text='Usuário que criou a tarefa. Definido na criação e imutável depois. Ao excluir a conta do criador, é anulado (SET_NULL), mas o nome permanece preservado em "creator_name".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='users.user', verbose_name='Criador'),
        ),
    ]
