# Generated by Django 6.0.6 on 2026-06-25 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_creator_name_alter_task_creator'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='responsibles',
        ),
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável pela tarefa (no máximo um; pode não haver nenhum). Ao excluir a conta do responsável, é anulado (SET_NULL).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='users.user', verbose_name='Responsável'),
        ),
    ]
